//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Assets.Resources
{
    using System;
    using System.ComponentModel;
    using System.Globalization;
    using System.Resources;
    using System.Threading;
    using Infrastructure.I18n;

    public class Labels
    {
        private static IResourceManager resourceManager;
        private static CultureInfo resourceCulture;

        [EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
        public static IResourceManager ResourceManager
        {
            get
            {
                if(resourceManager == null)
                {
                    IResourceManager temp = new ResourceManagerWrapper(new ResourceManager("Main.Assets.Resources.Labels", typeof(Labels).Assembly));
                    resourceManager = temp;
                }

                return resourceManager;
            }

            set
            {
                resourceManager = value;
            }
        }

        [EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        public static string LanguageSelection
        {
            get { return ResourceManager.GetString("LanguageSelection", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string NotificationUrl
        {
            get { return ResourceManager.GetString("NotificationUrl", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string Options
        {
            get { return ResourceManager.GetString("Options", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string TestConnection
        {
            get { return ResourceManager.GetString("TestConnection", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string ThemeSelection
        {
            get { return ResourceManager.GetString("ThemeSelection", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }
    }
}