//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipe.Assets.Resources
{
    using System;
    using System.ComponentModel;
    using System.Globalization;
    using System.Resources;
    using System.Threading;
    using Infrastructure.I18n;

    public class Labels
    {
        private static readonly object Sync = new object();
        private static IResourceManager resourceManager;
        private static CultureInfo resourceCulture;

        [EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
        public static IResourceManager ResourceManager
        {
            get
            {
                if(resourceManager == null)
                {
                    IResourceManager temp = new ResourceManagerWrapper(new ResourceManager("Recipe.Assets.Resources.Labels", typeof(Labels).Assembly));
                    resourceManager = temp;
                }

                return resourceManager;
            }

            set
            {
                resourceManager = value;
            }
        }

        [EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        public static string Label_Ingredient
        {
            get { return ResourceManager.GetString("Label_Ingredient", resourceCulture ?? Thread.CurrentThread.CurrentUICulture); }
        }

        public static string Label_Ingredients
        {
            get { return ResourceManager.GetString("Label_Ingredients", resourceCulture ?? Thread.CurrentThread.CurrentUICulture); }
        }

        public static string Label_Recipe
        {
            get { return ResourceManager.GetString("Label_Recipe", resourceCulture ?? Thread.CurrentThread.CurrentUICulture); }
        }

        public static string Label_Recipes
        {
            get { return ResourceManager.GetString("Label_Recipes", resourceCulture ?? Thread.CurrentThread.CurrentUICulture); }
        }
    }
}