//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipe.Assets.Resources
{
    using System;
    using System.ComponentModel;
    using System.Globalization;
    using System.Resources;
    using System.Threading;
    using Infrastructure.I18n;

    public class Labels
    {
        private static IResourceManager resourceManager;
        private static CultureInfo resourceCulture;

        [EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
        public static IResourceManager ResourceManager
        {
            get
            {
                if(resourceManager == null)
                {
                    IResourceManager temp = new ResourceManagerWrapper(new ResourceManager("Recipe.Assets.Resources.Labels", typeof(Labels).Assembly));
                    resourceManager = temp;
                }

                return resourceManager;
            }

            set
            {
                resourceManager = value;
            }
        }

        [EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        public static string Bar
        {
            get { return ResourceManager.GetString("Bar", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string Basil
        {
            get { return ResourceManager.GetString("Basil", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string Foo
        {
            get { return ResourceManager.GetString("Foo", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string Ingredient
        {
            get { return ResourceManager.GetString("Ingredient", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string Ingredients
        {
            get { return ResourceManager.GetString("Ingredients", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string Name
        {
            get { return ResourceManager.GetString("Name", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string Recipe
        {
            get { return ResourceManager.GetString("Recipe", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string Recipes
        {
            get { return ResourceManager.GetString("Recipes", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string Timestamp
        {
            get { return ResourceManager.GetString("Timestamp", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }
    }
}