//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cars.CodeQuality.Test.Properties
{
    using System;
    using System.ComponentModel;
    using System.Globalization;
    using System.Resources;
    using System.Threading;
    using Cars.I18n;

    public class Resources
    {
        private static IResourceManager resourceManager;
        private static CultureInfo resourceCulture;

        [EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
        public static IResourceManager ResourceManager
        {
            get
            {
                if(resourceManager == null)
                {
                    IResourceManager temp = new ResourceManagerWrapper(new ResourceManager("Cars.CodeQuality.Test.Properties.Resources", typeof(Resources).Assembly));
                    resourceManager = temp;
                }

                return resourceManager;
            }

            set
            {
                resourceManager = value;
            }
        }

        [EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        public static string NoResourceNameEndsWith
        {
            get { return Resources.ResourceManager.GetString("NoResourceNameEndsWith", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string NoResourceWithName
        {
            get { return Resources.ResourceManager.GetString("NoResourceWithName", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string RuleNotViolated
        {
            get { return Resources.ResourceManager.GetString("RuleNotViolated", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string SourceFileCouldNotBeAdded
        {
            get { return Resources.ResourceManager.GetString("SourceFileCouldNotBeAdded", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string ViolationsMessage
        {
            get { return Resources.ResourceManager.GetString("ViolationsMessage", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }
    }
}