extern alias CC30;

namespace TecX.Unity.TypedFactory
{
    using System;
    using System.Reflection;

    using CC30.Castle.DynamicProxy;

    using Microsoft.Practices.Unity;

    using TecX.Common;

    public class TypedFactoryExtension : UnityContainerExtension, ITypedFactoryConfiguration
    {
        private ProxyGenerator generator;

        public void RegisterFactory(Type factoryType, ITypedFactoryComponentSelector selector)
        {
            Guard.AssertNotNull(selector, "selector");

            Guard.AssertCondition(
                factoryType.IsInterface,
                factoryType,
                "factoryType",
                "Cannot generate an implementation for a non-interface factory type.");

            this.AssertNoMethodHasOutParams(factoryType);

            this.Container.RegisterType(factoryType, new InjectionFactory(container => GetAutoGeneratedFactory(factoryType, container, selector)));
        }

        protected override void Initialize()
        {
            this.generator = new ProxyGenerator();
        }

        private void AssertNoMethodHasOutParams(Type factoryType)
        {
            var methods = factoryType.GetMethods(BindingFlags.Instance | BindingFlags.Public);

            foreach (var method in methods)
            {
                foreach (var parameter in method.GetParameters())
                {
                    if (parameter.IsOut)
                    {
                        throw new ArgumentException("Methods in factory interface must not have out parameters", "TFactory");
                    }
                }
            }
        }

        private object GetAutoGeneratedFactory(Type factoryType, IUnityContainer container, ITypedFactoryComponentSelector selector)
        {
            return this.generator.CreateInterfaceProxyWithoutTarget(factoryType, new FactoryInterceptor(container, selector));
        }
    }
}
