//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Hydra.Infrastructure.Test
{
    public static class KnownTestFiles
    {
        public static class TestFiles
        {
            public static class Mails
            {
                /// <summary>
                /// Hydra.Infrastructure.Test.TestFiles.Mails.Mail01.eml
                /// </summary>
                public const string Mail01 = "Hydra.Infrastructure.Test.TestFiles.Mails.Mail01.eml";
            }
        }
    }
}