//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Hydra.Jobs.Test
{
    public static class KnownTestFiles
    {
        public static class Images
        {
            /// <summary>
            /// Hydra.Test.Images.Red.png
            /// </summary>
            public const string Red = "Hydra.Test.Images.Red.png";
        }

        public static class Texts
        {
            public static class Long
            {
                /// <summary>
                /// Hydra.Test.Texts.Long.AnotherLong.txt
                /// </summary>
                public const string AnotherLong = "Hydra.Test.Texts.Long.AnotherLong.txt";

                /// <summary>
                /// Hydra.Test.Texts.Long.VeryLong.txt
                /// </summary>
                public const string VeryLong = "Hydra.Test.Texts.Long.VeryLong.txt";
            }

            public static class Short
            {
                /// <summary>
                /// Hydra.Test.Texts.Short.VeryShort.txt
                /// </summary>
                public const string VeryShort = "Hydra.Test.Texts.Short.VeryShort.txt";
            }
        }
    }
}