//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cars.CodeQuality.Test
{
    public static class KnownTestFiles
    {
        public static class TestFiles
        {
            /// <summary>
            /// Cars.CodeQuality.Test.TestFiles.AsyncVoid.cs
            /// </summary>
            public const string AsyncVoid = "Cars.CodeQuality.Test.TestFiles.AsyncVoid.cs";

            /// <summary>
            /// Cars.CodeQuality.Test.TestFiles.CatchWithTypeOnly.cs
            /// </summary>
            public const string CatchWithTypeOnly = "Cars.CodeQuality.Test.TestFiles.CatchWithTypeOnly.cs";

            /// <summary>
            /// Cars.CodeQuality.Test.TestFiles.EmptyCatchWithoutType.cs
            /// </summary>
            public const string EmptyCatchWithoutType = "Cars.CodeQuality.Test.TestFiles.EmptyCatchWithoutType.cs";

            /// <summary>
            /// Cars.CodeQuality.Test.TestFiles.IncorrectRethrow.cs
            /// </summary>
            public const string IncorrectRethrow = "Cars.CodeQuality.Test.TestFiles.IncorrectRethrow.cs";

            /// <summary>
            /// Cars.CodeQuality.Test.TestFiles.ReturnsDefaultInt.cs
            /// </summary>
            public const string ReturnsDefaultInt = "Cars.CodeQuality.Test.TestFiles.ReturnsDefaultInt.cs";

            /// <summary>
            /// Cars.CodeQuality.Test.TestFiles.SetOnlyProperty.cs
            /// </summary>
            public const string SetOnlyProperty = "Cars.CodeQuality.Test.TestFiles.SetOnlyProperty.cs";

            /// <summary>
            /// Cars.CodeQuality.Test.TestFiles.TooManyConstructorArguments.cs
            /// </summary>
            public const string TooManyConstructorArguments = "Cars.CodeQuality.Test.TestFiles.TooManyConstructorArguments.cs";

            /// <summary>
            /// Cars.CodeQuality.Test.TestFiles.TooManyMethodArguments.cs
            /// </summary>
            public const string TooManyMethodArguments = "Cars.CodeQuality.Test.TestFiles.TooManyMethodArguments.cs";
        }
    }
}
