//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cars.CodeQuality
{
    public static class Constants
    {
        public static class Cars
        {
            public static class CodeQuality
            {
                public static class CodeQualityRules
                {
                    public const string Category = "Cars.CodeQuality.CodeQualityRules";

                    /// <summary>
                    /// ConstructorMustNotHaveMoreThanFourParameters
                    /// </summary>
                    public const string DV1000 = "DV1000:ConstructorMustNotHaveMoreThanFourParameters";

                    /// <summary>
                    /// MethodMustNotHaveMoreThanFourParameters
                    /// </summary>
                    public const string DV1001 = "DV1001:MethodMustNotHaveMoreThanFourParameters";

                    /// <summary>
                    /// IncorrectRethrow
                    /// </summary>
                    public const string DV1002 = "DV1002:IncorrectRethrow";

                    /// <summary>
                    /// DontUseDefaultOperator
                    /// </summary>
                    public const string DV1003 = "DV1003:DontUseDefaultOperator";

                    /// <summary>
                    /// AsyncMethodsMustReturnTask
                    /// </summary>
                    public const string DV1004 = "DV1004:AsyncMethodsMustReturnTask";

                    /// <summary>
                    /// DontDeclareSetOnlyProperties
                    /// </summary>
                    public const string DV1005 = "DV1005:DontDeclareSetOnlyProperties";
                }
            }
        }
    }
}