rmdir TecX.Agile\bin /S /Q
rmdir TecX.Agile.ChangeTracking\bin /S /Q
rmdir TecX.Agile.Data\bin /S /Q
rmdir TecX.Agile.Data.File\bin /S /Q
rmdir TecX.Agile.Data.Json\bin /S /Q
rmdir TecX.Agile.Data.Test\bin /S /Q
rmdir TecX.Agile.Data.Tfs\bin /S /Q
rmdir TecX.Agile.Data.Xml\bin /S /Q
rmdir TecX.Agile.Error\bin /S /Q
rmdir TecX.Agile.Infrastructure\bin /S /Q
rmdir TecX.Agile.Modules.Gestures\bin /S /Q
rmdir TecX.Agile.Modules.Main\bin /S /Q
rmdir TecX.Agile.Modules.SysInfo\bin /S /Q
rmdir TecX.Agile.Moduls.Speech\bin /S /Q
rmdir TecX.Agile.Peer\bin /S /Q
rmdir TecX.Agile.Peer.Test\bin /S /Q
rmdir TecX.Agile.Planner\bin /S /Q
rmdir TecX.Agile.Planner.Silverlight\bin /S /Q
rmdir TecX.Agile.Planner.Silverlight.Web\bin /S /Q
rmdir TecX.Agile.Push\bin /S /Q
rmdir TecX.Agile.Remote\bin /S /Q
rmdir TecX.Agile.Serialization\bin /S /Q
rmdir TecX.Agile.Serialization.Test\bin /S /Q
rmdir TecX.Agile.Server\bin /S /Q
rmdir TecX.Agile.Test\bin /S /Q
rmdir TecX.Agile.Undo\bin /S /Q
rmdir TecX.Agile.View\bin /S /Q
rmdir TecX.Agile.View.Silverlight\bin /S /Q
rmdir TecX.Agile.View.Test\bin /S /Q
rmdir TecX.Agile.ViewModel\bin /S /Q
rmdir TecX.Agile.ViewModel.Test\bin /S /Q
rmdir TecX.Common\bin /S /Q
rmdir TecX.Common.EntLib\bin /S /Q
rmdir TecX.Common.EntLib.Test\bin /S /Q
rmdir TecX.Common.Event\bin /S /Q
rmdir TecX.Common.Event.Unity\bin /S /Q
rmdir TecX.Common.Test\bin /S /Q
rmdir TecX.Common.Undo\bin /S /Q
rmdir TecX.Prism\bin /S /Q
rmdir TecX.ServiceModel.AutoMagic\bin /S /Q
rmdir TecX.ServiceModel.Test\bin /S /Q
rmdir TecX.ServiceModel.Unity\bin /S /Q
rmdir TecX.TestTools\bin /S /Q
rmdir TecX.TestTools.Test\bin /S /Q
rmdir TecX.Undo\bin /S /Q
rmdir TecX.Undo.Test\bin /S /Q
rmdir TecX.Unity\bin /S /Q
rmdir TecX.Unity.ContextualBinding\bin /S /Q
rmdir TecX.Unity.ContextualBinding.Test\bin /S /Q
rmdir TecX.Unity.Test\bin /S /Q
rmdir TecX.Unity.Test.Contract\bin /S /Q


rmdir TecX.Agile\obj /S /Q
rmdir TecX.Agile.ChangeTracking\obj /S /Q
rmdir TecX.Agile.Data\obj /S /Q
rmdir TecX.Agile.Data.File\obj /S /Q
rmdir TecX.Agile.Data.Json\obj /S /Q
rmdir TecX.Agile.Data.Test\obj /S /Q
rmdir TecX.Agile.Data.Tfs\obj /S /Q
rmdir TecX.Agile.Data.Xml\obj /S /Q
rmdir TecX.Agile.Error\obj /S /Q
rmdir TecX.Agile.Infrastructure\obj /S /Q
rmdir TecX.Agile.Modules.Gestures\obj /S /Q
rmdir TecX.Agile.Modules.Main\obj /S /Q
rmdir TecX.Agile.Modules.SysInfo\obj /S /Q
rmdir TecX.Agile.Moduls.Speech\obj /S /Q
rmdir TecX.Agile.Peer\obj /S /Q
rmdir TecX.Agile.Peer.Test\obj /S /Q
rmdir TecX.Agile.Planner\obj /S /Q
rmdir TecX.Agile.Planner.Silverlight\obj /S /Q
rmdir TecX.Agile.Planner.Silverlight.Web\obj /S /Q
rmdir TecX.Agile.Push\obj /S /Q
rmdir TecX.Agile.Remote\obj /S /Q
rmdir TecX.Agile.Serialization\obj /S /Q
rmdir TecX.Agile.Serialization.Test\obj /S /Q
rmdir TecX.Agile.Server\obj /S /Q
rmdir TecX.Agile.Test\obj /S /Q
rmdir TecX.Agile.Undo\obj /S /Q
rmdir TecX.Agile.View\obj /S /Q
rmdir TecX.Agile.View.Silverlight\obj /S /Q
rmdir TecX.Agile.View.Test\obj /S /Q
rmdir TecX.Agile.ViewModel\obj /S /Q
rmdir TecX.Agile.ViewModel.Test\obj /S /Q
rmdir TecX.Common\obj /S /Q
rmdir TecX.Common.EntLib\obj /S /Q
rmdir TecX.Common.EntLib.Test\obj /S /Q
rmdir TecX.Common.Event\obj /S /Q
rmdir TecX.Common.Event.Unity\obj /S /Q
rmdir TecX.Common.Test\obj /S /Q
rmdir TecX.Common.Undo\obj /S /Q
rmdir TecX.Prism\obj /S /Q
rmdir TecX.ServiceModel.AutoMagic\obj /S /Q
rmdir TecX.ServiceModel.Test\obj /S /Q
rmdir TecX.ServiceModel.Unity\obj /S /Q
rmdir TecX.TestTools\obj /S /Q
rmdir TecX.TestTools.Test\obj /S /Q
rmdir TecX.Undo\obj /S /Q
rmdir TecX.Undo.Test\obj /S /Q
rmdir TecX.Unity\obj /S /Q
rmdir TecX.Unity.ContextualBinding\obj /S /Q
rmdir TecX.Unity.ContextualBinding.Test\obj /S /Q
rmdir TecX.Unity.Test\obj /S /Q
rmdir TecX.Unity.Test.Contract\obj /S /Q