ALTER TABLE [dbo].[SearchTerms]
    ADD CONSTRAINT [IX_SearchTerms_Text] UNIQUE CLUSTERED ([SearchTerm] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

