ALTER TABLE [dbo].[Messages2SearchTerms]
    ADD CONSTRAINT [PK_AlarmLog2SearchTerms] PRIMARY KEY CLUSTERED ([MessageId] ASC, [SearchTermId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

