ALTER TABLE [dbo].[SearchTerms]
    ADD CONSTRAINT [PK_SearchTerms] PRIMARY KEY NONCLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

