using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.Practices.Unity;
using Microsoft.VisualStudio.TestTools.UnitTesting;

using TecX.TestTools;
using TecX.Unity.TypedFactory.Test.TestObjects;

namespace TecX.Unity.TypedFactory.Test
{
    public abstract class Given_ContainerWithTypedFactoryExtension : GivenWhenThen
    {
        protected IUnityContainer container;

        protected IFoo _foo;

        protected IMyFactory _factory;

        protected override void Given()
        {
            container = new UnityContainer();
            container.AddNewExtension<TypedFactoryExtension>();
            container.RegisterFactory<IMyFactory>();

            _factory = container.Resolve<IMyFactory>();
        }
    }

    public abstract class Given_ContainerWithFooRegistration : Given_ContainerWithTypedFactoryExtension
    {
        protected override void Given()
        {
            base.Given();

            container.RegisterType<IFoo, Foo>();
        }
    }

    [TestClass]
    public class When_UsingFactoryToCreateInstance : Given_ContainerWithFooRegistration
    {
        protected override void When()
        {
            _foo = _factory.Create();
        }

        [TestMethod]
        public void Then_AutoGeneratedProxyReturnsInstance()
        {
            Assert.IsNotNull(_foo);
        }
    }

    public abstract class Given_ContainerWithBarRegistration : Given_ContainerWithTypedFactoryExtension
    {
        protected override void Given()
        {
            base.Given();

            container.RegisterType<IFoo, Bar>();
        }
    }

    [TestClass]
    public class When_UsingFactoryWithParameterToCreateInstance : Given_ContainerWithBarRegistration
    {
        protected override void When()
        {
            _foo = _factory.Create("some name");
        }

        [TestMethod]
        public void Then_ParameterIsUsed()
        {
            Assert.IsNotNull(_foo);
            Assert.AreEqual("some name", _foo.Name);
        }
    }
}
