using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace TecX.Unity.TypedFactory.Test
{
    [TestClass]
    public class When_UsingFactoryToCreateInstance : Given_ContainerWithFooRegistration
    {
        protected override void When()
        {
            _foo = _factory.Create();
        }

        [TestMethod]
        public void Then_AutoGeneratedProxyReturnsInstance()
        {
            Assert.IsNotNull(_foo);
        }
    }
}