namespace TecX.Unity.TypedFactory.Test
{
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    [TestClass]
    public class When_UsingFactoryToCreateInstance : Given_ContainerWithFooRegistration
    {
        protected override void Act()
        {
            this.Foo = this.Factory.Create();
        }

        [TestMethod]
        public void Then_AutoGeneratedProxyReturnsInstance()
        {
            Assert.IsNotNull(this.Foo);
        }
    }
}