//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hydra.Properties
{
    using System;
    using System.ComponentModel;
    using System.Globalization;
    using System.Resources;
    using System.Threading;
    using Hydra.Infrastructure.I18n;

    public class Resources
    {
        private static IResourceManager resourceManager;
        private static CultureInfo resourceCulture;

        [EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
        public static IResourceManager ResourceManager
        {
            get
            {
                if(resourceManager == null)
                {
                    IResourceManager temp = new ResourceManagerWrapper(new ResourceManager("Hydra.Properties.Resources", typeof(Resources).Assembly));
                    resourceManager = temp;
                }

                return resourceManager;
            }

            set
            {
                resourceManager = value;
            }
        }

        [EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        public static string AvailableJobs
        {
            get { return Resources.ResourceManager.GetString("AvailableJobs", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string Book_Title
        {
            get { return Resources.ResourceManager.GetString("Book_Title", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string Create
        {
            get { return Resources.ResourceManager.GetString("Create", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string Delete
        {
            get { return Resources.ResourceManager.GetString("Delete", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string Edit
        {
            get { return Resources.ResourceManager.GetString("Edit", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string JobInfo_Description
        {
            get { return Resources.ResourceManager.GetString("JobInfo_Description", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string JobInfo_Name
        {
            get { return Resources.ResourceManager.GetString("JobInfo_Name", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string Schedule
        {
            get { return Resources.ResourceManager.GetString("Schedule", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }
    }
}