//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hydra.Infrastructure.Properties
{
    using System;
    using System.ComponentModel;
    using System.Globalization;
    using System.Resources;
    using System.Threading;
    using Hydra.Infrastructure.I18n;

    public class Resources
    {
        private static IResourceManager resourceManager;
        private static CultureInfo resourceCulture;

        [EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
        public static IResourceManager ResourceManager
        {
            get
            {
                if(resourceManager == null)
                {
                    IResourceManager temp = new ResourceManagerWrapper(new ResourceManager("Hydra.Infrastructure.Properties.Resources", typeof(Resources).Assembly));
                    resourceManager = temp;
                }

                return resourceManager;
            }

            set
            {
                resourceManager = value;
            }
        }

        [EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        public static string AppointmentCreatedWith
        {
            get { return Resources.ResourceManager.GetString("AppointmentCreatedWith", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string ConnectionStringNotFound
        {
            get { return Resources.ResourceManager.GetString("ConnectionStringNotFound", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string ConversionNotSupported
        {
            get { return Resources.ResourceManager.GetString("ConversionNotSupported", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string EnumerationDoesNotDeclareAnyFields
        {
            get { return Resources.ResourceManager.GetString("EnumerationDoesNotDeclareAnyFields", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string InitializationOfEnumerationFailed
        {
            get { return Resources.ResourceManager.GetString("InitializationOfEnumerationFailed", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string InvalidSettingName
        {
            get { return Resources.ResourceManager.GetString("InvalidSettingName", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string Reminder
        {
            get { return Resources.ResourceManager.GetString("Reminder", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string TranslationNotFound
        {
            get { return Resources.ResourceManager.GetString("TranslationNotFound", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }

        public static string ValidMailAddressRequired
        {
            get { return Resources.ResourceManager.GetString("ValidMailAddressRequired", resourceCulture ?? CultureInfo.CurrentUICulture); }
        }
    }
}